// <auto-generated />
using System;
using MecanicoConfiable.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MecanicoConfiable.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Auxiliar", b =>
                {
                    b.Property<int>("IdAuxiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuxiliar"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAuxiliar");

                    b.ToTable("Auxiliares");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.CambioRepuesto", b =>
                {
                    b.Property<int>("IdCambioRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCambioRepuesto"), 1L, 1);

                    b.Property<string>("FechaHora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.HasKey("IdCambioRepuesto");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("CambioRepuestos");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Conductor", b =>
                {
                    b.Property<int>("IdConductor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConductor"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdConductor");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Conductor");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Dueño", b =>
                {
                    b.Property<int>("IdDueño")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDueño"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDueño");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Dueños");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Mecanico", b =>
                {
                    b.Property<int>("IdMecanico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMecanico"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelEstudio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMecanico");

                    b.ToTable("Mecanicos");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Repuesto", b =>
                {
                    b.Property<int>("IdRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRepuesto"), 1L, 1);

                    b.Property<int>("IdCambioRepuesto")
                        .HasColumnType("int");

                    b.Property<string>("Repuest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRepuesto");

                    b.HasIndex("IdCambioRepuesto");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.RevisionNiveles", b =>
                {
                    b.Property<int>("IdNiveles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNiveles"), 1L, 1);

                    b.Property<string>("FechaHora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("NivelAceite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelLiquidDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelLiquidoFrenos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelRefrigerante")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNiveles");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("RevisionNiveles");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Seguro", b =>
                {
                    b.Property<int>("IdSeguro")
                        .HasColumnType("int");

                    b.Property<string>("FechaCompra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSeguro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorSeguro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSeguro");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"), 1L, 1);

                    b.Property<string>("DescripcionAdicional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMecanico")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("PaisOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("IdMecanico");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.CambioRepuesto", b =>
                {
                    b.HasOne("MecanicoConfiable.App.Dominio.Vehiculo", "Vehiculo")
                        .WithMany("CambioRepuesto")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Conductor", b =>
                {
                    b.HasOne("MecanicoConfiable.App.Dominio.Vehiculo", "Vehiculo")
                        .WithMany("Conductor")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Dueño", b =>
                {
                    b.HasOne("MecanicoConfiable.App.Dominio.Vehiculo", "Vehiculo")
                        .WithMany("Dueño")
                        .HasForeignKey("IdVehiculo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Repuesto", b =>
                {
                    b.HasOne("MecanicoConfiable.App.Dominio.CambioRepuesto", "CambioRepuesto")
                        .WithMany("Repuestos")
                        .HasForeignKey("IdCambioRepuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CambioRepuesto");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.RevisionNiveles", b =>
                {
                    b.HasOne("MecanicoConfiable.App.Dominio.Vehiculo", "Vehiculo")
                        .WithMany("RevisionNiveles")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Seguro", b =>
                {
                    b.HasOne("MecanicoConfiable.App.Dominio.Vehiculo", "Vehiculo")
                        .WithOne("Seguro")
                        .HasForeignKey("MecanicoConfiable.App.Dominio.Seguro", "IdSeguro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Vehiculo", b =>
                {
                    b.HasOne("MecanicoConfiable.App.Dominio.Mecanico", "Mecanico")
                        .WithMany("Vehiculo")
                        .HasForeignKey("IdMecanico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.CambioRepuesto", b =>
                {
                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Mecanico", b =>
                {
                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MecanicoConfiable.App.Dominio.Vehiculo", b =>
                {
                    b.Navigation("CambioRepuesto");

                    b.Navigation("Conductor");

                    b.Navigation("Dueño");

                    b.Navigation("RevisionNiveles");

                    b.Navigation("Seguro");
                });
#pragma warning restore 612, 618
        }
    }
}
